#define DRIVER_NAME "axidriver"

#define DRIVER_DMA_SIZE_OF_ONE_BUFFER		( 128*1024 )			// this is the max value. user can set it to smaller numbers using ioctl
#define DRIVER_DMA_NUMBER_OF_BUFFERS_S2MM	1
#define DRIVER_DMA_NUMBER_OF_BUFFERS_MM2S	1

#define IOCTL_MY_DMA_MAGIC				'r'
#define IOCTL_MY_DMA_SET_TRANSFER_BLOCK_SIZE		_IOW ( IOCTL_MY_DMA_MAGIC, 0, int )
#define IOCTL_MY_DMA_ALLOCATE_COHERENT_MEMORY		_IOW ( IOCTL_MY_DMA_MAGIC, 1, int )
#define IOCTL_MY_DMA_SET_NUMBER_OF_BLOCKS_TO_MM2S	_IOW ( IOCTL_MY_DMA_MAGIC, 2, int )
#define IOCTL_MY_DMA_SET_NUMBER_OF_BLOCKS_TO_S2MM	_IOW ( IOCTL_MY_DMA_MAGIC, 3, int )
#define IOCTL_MY_DMA_START_S2MM				_IOW ( IOCTL_MY_DMA_MAGIC, 4, int )
#define IOCTL_MY_DMA_START_MM2S				_IOW ( IOCTL_MY_DMA_MAGIC, 5, int )
#define IOCTL_MY_DMA_GET_S2MM_POINTER			_IOR ( IOCTL_MY_DMA_MAGIC, 6, int )
#define IOCTL_MY_DMA_GET_MM2S_POINTER			_IOR ( IOCTL_MY_DMA_MAGIC, 7, int )
#define IOCTL_MY_DMA_SET_S2MM_MMAP			_IOW ( IOCTL_MY_DMA_MAGIC, 8, int )
#define IOCTL_MY_DMA_SET_MM2S_MMAP			_IOW ( IOCTL_MY_DMA_MAGIC, 9, int )
#define IOCLT_MY_DMA_SET_BUFFER_NO_MMAP			_IOW ( IOCTL_MY_DMA_MAGIC,10, int )
#define IOCTL_MY_DMA_RELEASE_COHERENT_MEMORY 		_IOW ( IOCTL_MY_DMA_MAGIC,11, int )
#define IOCTL_MY_DMA_DISABLE_ISR_MESSAGES		_IOW ( IOCTL_MY_DMA_MAGIC,12, int )
#define IOCTL_MY_DMA_SET_NUMBER_OF_BUFFERS_MM2S		_IOW ( IOCTL_MY_DMA_MAGIC,13, int )
#define IOCTL_MY_DMA_SET_NUMBER_OF_BUFFERS_S2MM		_IOW ( IOCTL_MY_DMA_MAGIC,14, int )
#define IOCTL_MY_DMA_DUMP_REGS				_IOW ( IOCTL_MY_DMA_MAGIC,15, int )
#define IOCTL_MY_DMA_RESET				_IOW ( IOCTL_MY_DMA_MAGIC,16, int )
#define IOCTL_CHECK_STATUS        _IOW ( IOCTL_MY_DMA_MAGIC,17, int )
#define IOCTL_INTR_HELPER       _IOW ( IOCTL_MY_DMA_MAGIC,18, int )

// DMA regs offset values (dma in register mode.)
#define MM2S_DMA_CR 			0x0
#define MM2S_DMA_SR 			0x4

#define S2MM_DMA_CR 			0x30
#define S2MM_DMA_SR 			0x34

#define MM2S_SOURCE_ADDRESS_LSB 	0x18
#define MM2S_SOURCE_ADDRESS_MSB		0x1C

#define S2MM_DEST_ADDRESS_LSB 		0x48
#define S2MM_DEST_ADDRESS_MSB		0x4C

#define MM2S_LENGTH			0x28
#define S2MM_LENGTH			0x58
